// <auto-generated />
using System;
using System.Collections.Generic;
using Capstone.Procurement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capstone.Procurement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    [Migration("20260916065922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Capstone.Procurement.Domain.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Consumed", "Capstone.Procurement.Domain.PurchaseOrder.Consumed#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Consumed_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Consumed_Currency");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Lines", "Capstone.Procurement.Domain.PurchaseOrder.Lines#PurchaseOrderLine", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ItemReference")
                                .IsRequired();

                            b1.Property<int>("LineNumber");

                            b1.Property<int>("OrderedQuantity");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "Capstone.Procurement.Domain.PurchaseOrder.Lines#PurchaseOrderLine.UnitPrice#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("Lines")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Reserved", "Capstone.Procurement.Domain.PurchaseOrder.Reserved#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Reserved_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Reserved_Currency");
                        });

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrders", "procurement");
                });
#pragma warning restore 612, 618
        }
    }
}
