// <auto-generated />
using System;
using System.Collections.Generic;
using Capstone.Invoicing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capstone.Invoicing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvoicingDbContext))]
    partial class InvoicingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Capstone.Invoicing.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DisputeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Approval", "Capstone.Invoicing.Domain.Invoice.Approval#ApprovalRecord", b1 =>
                        {
                            b1.Property<DateTimeOffset>("ApprovedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Approval_ApprovedAt");

                            b1.Property<Guid?>("ApprovedBy")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Approval_ApprovedBy");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Approval_Kind");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Lines", "Capstone.Invoicing.Domain.Invoice.Lines#InvoiceLineItem", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BilledQuantity");

                            b1.Property<int>("PurchaseOrderLineNumber");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "Capstone.Invoicing.Domain.Invoice.Lines#InvoiceLineItem.UnitPrice#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("Lines")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MatchResult", "Capstone.Invoicing.Domain.Invoice.MatchResult#MatchResult", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("WithinTolerance");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "LineVariances", "Capstone.Invoicing.Domain.Invoice.MatchResult#MatchResult.LineVariances#LineVariance", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("LineNumber");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Invoiced", "Capstone.Invoicing.Domain.Invoice.MatchResult#MatchResult.LineVariances#LineVariance.Invoiced#Money", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<decimal>("Amount");

                                            b3.Property<string>("Currency")
                                                .IsRequired();
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "PurchaseOrderLineValue", "Capstone.Invoicing.Domain.Invoice.MatchResult#MatchResult.LineVariances#LineVariance.PurchaseOrderLineValue#Money", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<decimal>("Amount");

                                            b3.Property<string>("Currency")
                                                .IsRequired();
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Variance", "Capstone.Invoicing.Domain.Invoice.MatchResult#MatchResult.LineVariances#LineVariance.Variance#Money", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<decimal>("Amount");

                                            b3.Property<string>("Currency")
                                                .IsRequired();
                                        });
                                });

                            b1
                                .ToJson("MatchResult")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Terms", "Capstone.Invoicing.Domain.Invoice.Terms#PaymentTermsSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("NetDays")
                                .HasColumnType("int")
                                .HasColumnName("Terms_NetDays");

                            b1.Property<int>("ReviewWindowDays")
                                .HasColumnType("int")
                                .HasColumnName("Terms_ReviewWindowDays");
                        });

                    b.HasKey("Id");

                    b.ToTable("Invoices", "invoicing");
                });
#pragma warning restore 612, 618
        }
    }
}
